name: Postman collection

on: 
  push:
    branches: [ master ]
    
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - run: |
          npm install -g newman     
          
    test: # make sure the action works on a clean machine without building
      runs-on: ubuntu-latest
      needs: build
      steps: 
      - uses: actions/checkout@v1

      - name: Run Newman
        id: run-api-tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: ./Tests.postman_collection.json
          environment: ./PetStore.postman_environment.json
          path: jest-junit.xml
          reporters: cli
          reporter: jest-junit

      - name: Export Summary from Outputs
        run: |
          echo ${{ steps.run-api-tests.outputs.summary }}
          
          
      - name: Send Email
        uses: wadeww/send-email-action@master
        with: 
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: taliana.slava@gmail.com
          from: Me 
      
      
    report:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - uses: dorny/test-reporter@v1
        with:
          #rtifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results 


    
    
