name: Postman collection

on: 
  push:
    branches: [ master ]
    
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - run: |
          npm install -g newman     
          
    test: # make sure the action works on a clean machine without building
      runs-on: ubuntu-latest
      needs: build
      steps: 
      - uses: actions/checkout@v1

      - name: Run Newman
        id: run-api-tests
        uses: anthonyvscode/newman-action@v1
        with:
          collection: ./Tests.postman_collection.json
          environment: ./PetStore.postman_environment.json
          path: jest-junit.xml
          reporters: cli
          reporter: jest-junit

      - name: Export Summary from Outputs
        run: |
          echo ${{ steps.run-api-tests.outputs.summary }}
          
          
      - name: Send Email
        uses: dawidd6/action-send-mail@v1.3.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Report of PetStore
          body: ${{ github.actor }} just starred your mail-on-star repo!!! ${{ github.repository }}
          to: ${{secrets.EMAIL_USERNAME }}
          from: ${{secrets.EMAIL_USERNAME }}
      
      
    report:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results 


    
    
