name: Postman collection

on: 
  push:
    branches: [ master ]
    
jobs:
    build:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@v1
      - run: npm install -g newman
          
    test: # make sure the action works on a clean machine without building
      needs: build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1

      - name: Run Newman
        id: run-api-tests
        uses: ./
        with:
          collection: https://github.com/taliana-slava/PetStore/blob/master/Tests.postman_collection.json
          environment: https://github.com/taliana-slava/PetStore/blob/master/PetStore.postman_environment.json
          reporters: cli

      - name: Export Summary from Outputs
        run: |
          echo ${{ steps.run-api-tests.outputs.summary }}


    
    
