name: Postman collection

on: 
  push:
    branches: [ main ]
    
jobs:
  API_test_collection:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: https://github.com/taliana-slava/PetStore/blob/main/Tests.postman_collection.json
        environment: https://github.com/taliana-slava/PetStore/blob/main/PetStore.postman_environment.json
        reporters: cli

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}
      

    
    
